### ISSUE TITLE
Cannot read property '_rawResponse' of null

### ISSUE THREAD

**Issue by akappel** [warseph/soap-as-promised#4] opened 2016-04-14 16:04 UTC
When sending a message with the client returned from `createClient(...)`, I receive the following error message:

```
D:\git-projects\message-simulator\node_modules\soap-as-promised\soap-as-promised.js:16
          console.log(typeof result._rawResponse);
                                   ^

TypeError: Cannot read property '_rawResponse' of null
    at nodeCallback (D:\git-projects\message-simulator\node_modules\soap-as-promised\soap-as-promised.js:16:36)
    at D:\git-projects\message-simulator\node_modules\soap-as-promised\node_modules\soap\lib\client.js:145:7
    at D:\git-projects\message-simulator\node_modules\soap-as-promised\node_modules\soap\lib\client.js:304:7
    at Request._callback (D:\git-projects\message-simulator\node_modules\soap-as-promised\node_modules\soap\lib\http.js:109:5)
    at Request.self.callback (D:\git-projects\message-simulator\node_modules\request\request.js:200:22)
    at emitTwo (events.js:100:13)
    at Request.emit (events.js:185:7)
    at Request.<anonymous> (D:\git-projects\message-simulator\node_modules\request\request.js:1046:10)
    at emitOne (events.js:95:20)
    at Request.emit (events.js:182:7)
```

I switched back to using vanilla node-soap and this error does not occur. Debugging in VS Code shows me that `result._rawResponse` is undefined as well as the `raw` value in the parameter.

Here is the code block in question:
```
function nodeCallback(err, result, raw) {
        if (err) {
          reject(err);
        } else {
          result._rawResponse = raw;
          resolve(result);
        }
}
```

**Comment by lightning18** [comment] 2016-04-20 03:43
I'm getting exactly the same error. @akappel, how did you work around it?

**Comment by warseph** [comment] 2016-04-22 03:28
Hi @akappel & @lightning18, 
I added a test to make sure it works, from what I can see the error seems to be result is not set, so I can't really help you find where the problem is without seeing more code.
In any case, if it was indeed an error on the library it seems to be fixed now, so please try with the latest version (1.14.1).
If it still doesn't work now, check the test I made to make sure you are using it correctly, and if you can reproduce it in a new test, or provide me with a bit more code to debug, I'll try to fix it, or help you fix it on your side.

**Comment by lightning18** [comment] 2016-04-22 04:23
Yes, soap-as-promised@1.14.2 fixed it for me. Thanks.

**Comment by warseph** [comment] 2016-04-22 12:30
Great! I'll close the issue then.

**Closed by warseph** 2016-04-22 12:30 UTC

**Comment by akappel** [comment] 2016-04-24 19:42
Hey @warseph thanks for the reply, I'll check out the new version when I get a chance. @lightning18 I had reverted back to using node-soap for the time being.
